name: Go GO Go 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
# Checkout source code
    - uses: actions/checkout@v2

    - name: build
      run: docker build -t kvalitetsit/kitcaddy:dev . 

# Login to docker hub using secrets in GitHub.
  #   - name: Login to docker
  #     uses: docker/login-action@v1
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}

  #   - name: Tag dev
  #     run: docker tag kvalitetsit/medcom-video-api:latest jonaspkit/video-api-test:dev

  #   - name: Push to docker
  #     run: docker push jonaspkit/video-api-test:dev

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     name: hej hej
  #     run: docker image ls
